parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\ApiUserProvider:
        arguments:
            $apiKeys: '%env(json:CLIENT_API_KEYS)%'

    GeoIp2\ProviderInterface:
        class: GeoIp2\Database\Reader
        arguments:
            $filename: '%env(resolve:GEOIP2_DATABASE_FILE)%'
            $locales:
                - en
